### ISSUE TITLE
Unable to discover peer over 1 hop

### ISSUE THREAD

**Issue by cowherdboy** [servalproject/mesh-extender-builder#6]
I have installed the mesh extender firmware on two MR3020 (A & B) units. I do not have the UHF module. I have changed the SSID of the AP on the B unit. I can SSH into the unit and ping the MESH IPs (adhoc0 interface). I then connected one handphone to unit A and a second handphone to unit B via the WiFi AP. The handphones are running Serval app ver. 0.93. When I go to Contacts > List Phone on the Mesh, I am unable to see the other phone. Can you let me know what could be the problem. I have no problem seeing the peer when both the phones are on the same AP, i.e. using only one unit of MR3020.

**Comment by gardners** [comment]
Hello,

Can you run:

servald id peers

from on the Mesh Extenders?

This will show if they can see each other.

Meanwhile, which commit of the Mesh Extender firmware are you running?
The Mesh Extender firmware is still under heavy and active development, so
you should aim to have the latest firmware changes on there.

Paul.

**Comment by cowherdboy** [comment]
Hi Paul,

I followed the instructions at:
http://developer.servalproject.org/dokuwiki/doku.php?id=content:meshextender:prototyping_on_mr3020

The git clone was done on Tuesday, 24th May. How do I find out which version I am running? I ran servald but got "servald: not found". Please let me know how to proceed.

FYI, The ./flash-virgin-mr3020 command did not work for me as it kept loading the stock firmware. So I did the flashing from WebGUI.

**Comment by gardners** [comment]
Hello,

Sounds like servald is not being put on the memory stick for some reason.
You do have a USB memory stick insterted, and have partitioned and
populated it?

Paul.

**Comment by gardners** [comment]
If you can type:

git log | head -20 in the mesh-extender-builder directory you used, that
will be helpful, so that I know exactly which commit you are working from.

Paul.

**Comment by cowherdboy** [comment]
Yes, I have the USB memory stick partitioned and populated. Here is the filesystem on the MR3020:

root@Serval-MeshExtender-0:~# df
Filesystem           1K-blocks      Used Available Use% Mounted on
rootfs                     576       232       344  40% /
/dev/root                 2560      2560         0 100% /rom
tmpfs                    14608        96     14512   1% /tmp
tmpfs                      512         0       512   0% /dev
/dev/mtdblock3             576       232       344  40% /overlay
overlayfs:/overlay         576       232       344  40% /
/dev/sda1              1046516        20   1046496   0% /dos
/dev/sda2              1045804    177552    815824  18% /serval
/dev/sda3              5701916    215488   5200504   4% /serval-var

Here is the git log output:

~/mesh-extender-builder$ git log | head -20
commit 33e6873350bdeab690eaa5c399c92476c2afcb08
Author: gardners paul@servalproject.org
Date:   Mon May 23 11:37:24 2016 +0930

```
read SID from keyring file to avoid problems with non-responsive servald.
remove timestamp check for lbard, since meshms sent by mesh extenders
will have crazy 1970 timestamps much of the time).
```

commit ead9aa3718a16e4c16798c702ea5d05b269be13e
Author: gardners paul@servalproject.org
Date:   Mon May 23 11:21:17 2016 +0930

```
pull in updated mesh-extender binaries
```

commit 52c500780ab9306f76db86582cc3c590d5d28f71
Author: gardners paul@servalproject.org
Date:   Mon May 23 11:16:57 2016 +0930

```
pull in updated mesh-extender binaries
```

**Comment by gardners** [comment]
Is there a servald binary in the /serval partition on the memory stick?

Paul.

**Comment by cowherdboy** [comment]
No. I don't see a servald binary.

root@Serval-MeshExtender-0:/serval# find . -name "serval*"
./www/software/source/files/serval-docs.tgz
./www/software/source/files/serval-dna.tgz
./www/software/android/servalmesh.apk

**Comment by gardners** [comment]
Ok, so the USB stick populating has not gone correctly for some reason.

Is there a servald binary in the servald directory in your
mesh-extender-builder directory that you used to install from?

Paul.

**Comment by cowherdboy** [comment]
I can't find servald binary. How can I build servald?

~/mesh-extender-builder/servald$ ls -al
total 540
drwxrwxr-x  2    4096 May 25 03:48 .
drwxrwxr-x 12    4096 May 26 16:14 ..
-rwxrwxr-x  1   52720 May 25 03:48 flash900
-rwxrwxr-x  1  304895 May 25 03:48 lbard
-rw-rw-r--  1   89220 May 25 03:48 rfd900-43-91.ihx
-rw-rw-r--  1  88488 May 25 03:48 rfd900-82-91.ihx
-rwxrwxr-x  1   464 May 25 03:48 serval.conf

**Comment by gardners** [comment]
I've added the missing binary.  To compile it yourself, you need to
cross-compile it using an openwrt build environment. That process is
documented somewhere, but I agree that we need to get the documentation
better and all in one place. It would also be nice to have all of the
cross-compilation scripts in the mesh-extender-build repository, so that
you can just "make servald/servald", instead of having binary artifacts in
the git repository, which even I know isn't a great idea.

Paul.

**Comment by cowherdboy** [comment]
Thanks Paul for your prompt support. It is working now.
